[package]
name = "chip8emu"
version = "0.1.0"
edition = "2021"
authors = ["henry-sm"]
lib = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
minifb = "0.19"

[workspace]

